spring.application.name: backend

spring.cloud.aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      enabled: true
    dynamodb:
      region: ${AWS_REGION}

moments:
  s3:
    bucket: ${BUCKET_NAME}
